
const ADD_TODO = 'ADD TODO';
const ADD_TODO_SUCCESS = 'ADD TODO SUCCESS';
const LOAD_TODOS = 'LOAD TODOS';
const TOGGLE_TODO = 'TOGGLE TODO';
const MARK_TODO_AS_DONE = 'MARK TODO AS DONE';

export {
  ADD_TODO,
  ADD_TODO_SUCCESS,
  LOAD_TODOS,
  TOGGLE_TODO,
  MARK_TODO_AS_DONE
};
